import sys
sys.stdout.reconfigure(encoding='utf-8')

with open('src/DemoNavy.jsx', 'r', encoding='utf-8') as f:
    content = f.read()

# ── OPERATION 1: Replace APP_SCENARIOS array ──────────────────────────────────
si = content.find('const APP_SCENARIOS = [')
ei = content.find('];\n\nconst Applications', si)
if si == -1 or ei == -1:
    print(f"ERROR si={si} ei={ei}")
    sys.exit(1)

new_array = """\
const APP_SCENARIOS = [

  // \u2500\u2500\u2500 PERSONAL ASSISTANT AGENT \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

  { id: "a01", agentType: "assistant", roles: ["founder","sales","executive"], domains: ["pipeline","cs"],
    plan: "early", planLabel: "Early Plan \u00b7 $35 /mo",
    title: "Call in 20 minutes. Agent has no idea your champion left.",
    scenario: "You\u2019ve got a board call with your biggest account in 20 minutes. PA agent sends a briefing \u2014 attendee list, last contact date. It doesn\u2019t mention that your main champion moved to a new company 11 days ago, or that two commitments from your side are still open.",
    withMemory: "Pulls last meeting notes and attendee names. No signal on what\u2019s shifted in the org or relationship since your last touchpoint.",
    withGenios: "Relationship health score, org change flagged 11 days ago, open commitments from your side, and a recommended opening move \u2014 delivered before the call starts.",
    theOneThing: "Memory prepares you for the meeting. GeniOS tells you how to walk in.",
    whyItMatters: "The first 90 seconds sets the agenda. Walking in with a champion who left costs you control of the room.",
    impact: "Avg 4 hrs/week saved on manual pre-call research across active accounts.",
    graphs: "Relationship \u00b7 State \u00b7 Precedent",
  },
  { id: "a02", agentType: "assistant", roles: ["founder","sales","executive"], domains: ["pipeline","cs"],
    plan: "early", planLabel: "Early Plan \u00b7 $35 /mo",
    title: "Follow-up queued to someone who left the company.",
    scenario: "PA agent drafts a follow-up to Rahul, your champion at a key account. What it doesn\u2019t tell you: Rahul changed companies 8 days ago. The email is about to land in an inbox no one reads.",
    withMemory: "Recalls the contact\u2019s name and last interaction. Drafts and queues the email. No mechanism to detect org changes at external companies.",
    withGenios: "State graph: contact\u2019s role changed 8 days ago. Authority graph updates to the new decision-maker. Recommends: hold outreach, confirm new contact before sending.",
    theOneThing: "Memory knows who you emailed. GeniOS knows if they still matter.",
    whyItMatters: "Emailing someone who left is a trust signal \u2014 it tells their team you\u2019re not paying attention. The relationship cost is silent and compounding.",
    impact: "Caught in 100% of cases where org change is detectable before outreach fires.",
    graphs: "State \u00b7 Authority \u00b7 Relationship",
  },
  { id: "a03", agentType: "assistant", roles: ["founder","executive"], domains: ["pipeline","strategy"],
    plan: "early", planLabel: "Early Plan \u00b7 $35 /mo",
    title: "You promised an investor an update by Friday. It\u2019s Friday.",
    scenario: "Three days ago you told an angel investor over email that you\u2019d send a monthly update \u2018by end of week.\u2019 Today is Friday afternoon. Your PA agent has no idea you said that \u2014 no reminder, no draft, no nudge.",
    withMemory: "Memory doesn\u2019t extract commitments from email threads. It stores messages, not what they obligate you to do.",
    withGenios: "Commitment extracted at ingest. Push delivered at T-24h with a pre-generated draft tailored to what this specific investor cares about most.",
    theOneThing: "Memory stores messages. GeniOS extracts the commitments hidden inside them.",
    whyItMatters: "Missed investor commitments compound. The first one is forgiven. The second one becomes a pattern that defines your relationship.",
    impact: "Zero missed commitments vs. avg 2.3 per month in orgs without GeniOS.",
    graphs: "Precedent \u00b7 State",
  },
  { id: "a04", agentType: "assistant", roles: ["founder","sales","executive"], domains: ["cs","pipeline"],
    plan: "early", planLabel: "Early Plan \u00b7 $35 /mo",
    title: "Your top customer\u2019s email filed as \u2018reply Monday\u2019.",
    scenario: "80 emails to triage. PA agent marks your top customer\u2019s renewal question as low priority. Flags a VC newsletter as urgent because they emailed twice. Your $200K account waits three days.",
    withMemory: "Triages by keywords and sender frequency. Doesn\u2019t know who actually matters to the business or what\u2019s at stake in each thread.",
    withGenios: "Every sender carries a relationship weight, authority score, and deal status. Top customer renewal: reply now. VC newsletter: archive. CFO thread: escalate.",
    theOneThing: "Keyword triage is fast. Context-aware triage is accurate.",
    whyItMatters: "A customer who waited 3 days for a reply on a renewal question already knows where they stand. That silence is your answer too.",
    impact: "Avg 1.2 mis-prioritized critical threads caught and corrected per day.",
    graphs: "Relationship \u00b7 Authority",
  },
  { id: "a05", agentType: "assistant", roles: ["founder","sales","executive"], domains: ["pipeline","cs"],
    plan: "early", planLabel: "Early Plan \u00b7 $35 /mo",
    title: "Scheduled product email fires mid-negotiation.",
    scenario: "You\u2019ve been in a back-and-forth renewal negotiation with your anchor customer for 10 days \u2014 pricing, terms, SLA. While that\u2019s in flight, your PA agent fires a scheduled \u2018product update\u2019 email to their CEO. Same person. Same moment.",
    withMemory: "No awareness of the active negotiation. Sends the scheduled email on time because the calendar said to.",
    withGenios: "State graph: active renewal negotiation in progress \u2014 outreach hold applied automatically. Email suppressed. Account owner notified.",
    theOneThing: "Memory doesn\u2019t know what\u2019s in-flight. GeniOS reads your org\u2019s active state before it acts.",
    whyItMatters: "A product pitch email mid-negotiation signals your teams don\u2019t talk to each other. That signal arrives before the actual damage does.",
    impact: "Prevents avg 3 misfire automated emails per month during active deal cycles.",
    graphs: "State \u00b7 Relationship",
  },
  { id: "a06", agentType: "assistant", roles: ["founder","sales","executive"], domains: ["cs","pipeline"],
    plan: "early", planLabel: "Early Plan \u00b7 $35 /mo",
    title: "Recap sent with zero memory of the last 3 sessions.",
    scenario: "PA agent writes the post-call recap. It accurately captures today\u2019s conversation. It says nothing about the commitment you made last month that still isn\u2019t done, or the issue the customer raised twice in prior sessions.",
    withMemory: "Summarizes today\u2019s call. No awareness of what was promised in prior sessions or whether past commitments have been honored.",
    withGenios: "Pulls full relationship context: outstanding commitments, what was said last time, what\u2019s changed. Recap shows what was honored, what\u2019s still open, and what\u2019s new.",
    theOneThing: "Your customer remembers every session. Your recap shouldn\u2019t be meeting them for the first time.",
    whyItMatters: "Customers notice when you don\u2019t reference what you promised. Recaps are a trust signal \u2014 they show whether you were paying attention.",
    impact: "100% commitment continuity across meeting recaps for tracked accounts.",
    graphs: "Precedent \u00b7 Relationship",
  },
  { id: "a07", agentType: "assistant", roles: ["founder","sales","executive"], domains: ["cs"],
    plan: "early", planLabel: "Early Plan \u00b7 $35 /mo",
    title: "Renewal call booked into a cooling relationship.",
    scenario: "PA agent books a renewal call for next week. Nobody flagged that the account\u2019s engagement has been dropping for 30 days and the main contact stopped replying 3 weeks ago. You\u2019re walking into a pitch when you should be walking into a repair.",
    withMemory: "Books the available slot. No awareness of relationship health or what\u2019s changed in the account since the last call.",
    withGenios: "Relationship graph: engagement dropped 44% over 30 days. Flags before booking: recommend human-led repair outreach first. Do not open with a renewal pitch.",
    theOneThing: "A calendar tool sees availability. GeniOS sees whether you should show up at all.",
    whyItMatters: "A renewal pitch to a cooling account doesn\u2019t just fail \u2014 it often accelerates the churn by confirming the customer\u2019s suspicion that you\u2019re not paying attention.",
    impact: "Relationship health flagged pre-booking in 100% of at-risk renewal accounts.",
    graphs: "Relationship \u00b7 State",
  },
  { id: "a08", agentType: "assistant", roles: ["founder"], domains: ["strategy","pipeline"],
    plan: "early", planLabel: "Early Plan \u00b7 $35 /mo",
    title: "Re-approaching a VC who passed 5 months ago with a generic email.",
    scenario: "PA agent drafts a fundraising email to a partner at Sequoia you met at a conference. That partner passed 5 months ago \u2014 specifically said \u2018come back when you have 6 months of revenue.\u2019 Your agent doesn\u2019t know. The email leads with a product update.",
    withMemory: "No recall of prior conversations outside the current context window. Drafts an outreach that ignores the prior pass entirely.",
    withGenios: "Precedent graph: investor passed 5 months ago \u2014 cited \u2018too early, come back with revenue.\u2019 Recommends: lead with month-6 revenue milestone. Address the exact concern they raised.",
    theOneThing: "Re-approaching a VC without addressing their exact rejection reason tells them you weren\u2019t listening the first time.",
    whyItMatters: "Second passes are harder to reverse. The right framing can reopen the conversation; the wrong one closes it for good.",
    impact: "100% of prior VC passes surfaced before re-outreach is drafted.",
    graphs: "Precedent \u00b7 Relationship",
  },
  { id: "a09", agentType: "assistant", roles: ["founder","executive"], domains: ["pipeline","strategy"],
    plan: "early", planLabel: "Early Plan \u00b7 $35 /mo",
    title: "Lunch invite declined. That person could unblock your stalled deal.",
    scenario: "PA agent declines a lunch invite from a key account\u2019s VP of Engineering \u2014 your calendar shows you\u2019re busy. That VP is the one person who can unblock a renewal that\u2019s been stuck in legal review for 6 weeks. The invite is gone.",
    withMemory: "Checks calendar availability. You\u2019re blocked. Declines on your behalf. No awareness of who the sender is or what\u2019s at stake.",
    withGenios: "Relationship graph: VP is the authority on the stalled renewal. State graph: deal in legal limbo 6 weeks. GeniOS flags before declining: this contact is high-value. Recommends counter with a specific time instead.",
    theOneThing: "A calendar tool manages your time. GeniOS manages what your time is worth.",
    whyItMatters: "An auto-declined invite from the one person who can unblock a deal is a 6-week delay you\u2019ll never trace back to a scheduling agent.",
    impact: "High-relationship contacts flagged before calendar declines on 100% of active deal accounts.",
    graphs: "Relationship \u00b7 State \u00b7 Authority",
  },
  { id: "a10", agentType: "assistant", roles: ["founder","sales"], domains: ["pipeline","cs"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Deal closed. Thank-you email reads like you just met.",
    scenario: "Six months. Three near-collapses. Two internal champions who fought for you. Deal finally closes. PA agent drafts the thank-you email \u2014 it\u2019s polished, professional, and completely generic. No reference to any of it.",
    withMemory: "Writes a well-formatted email. No context on the relationship arc, what was overcome, or who championed the deal internally.",
    withGenios: "Relationship graph: 6-month journey, 3 near-losses, 2 internal champions identified. Email references the specific moment that turned the deal \u2014 grounded in your actual history.",
    theOneThing: "A generic thank-you after 6 months is worse than no thank-you \u2014 it signals you weren\u2019t paying attention.",
    whyItMatters: "The close is the beginning of the renewal. How you end the sale determines how you enter the relationship.",
    impact: "Relationship-aware close communications correlate with 2.4\u00d7 higher renewal rates.",
    graphs: "Relationship \u00b7 Precedent",
  },

  // \u2500\u2500\u2500 SALES AGENT \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

  { id: "s01", agentType: "sales", roles: ["founder","sales","executive"], domains: ["pipeline","cs"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Follow-up sent while their CEO transition is still live.",
    scenario: "You\u2019ve been courting this company for 3 months. Sales agent sends a scheduled follow-up. Their CEO resigned 9 days ago \u2014 the org is frozen, leadership is unsettled, nobody is making decisions. Your email lands in the middle of it.",
    withMemory: "Recalls last email date and account status. Drafts and sends the follow-up on schedule. No awareness of what\u2019s happening at the prospect\u2019s org.",
    withGenios: "State graph: leadership transition active \u2014 CEO departed 9 days ago. Relationship graph: engagement cooling. Recommends: hold outreach 14 days, route to CSM for a temperature check.",
    theOneThing: "Memory sees a warm account. GeniOS sees a company mid-crisis.",
    whyItMatters: "Outreach during a leadership transition reads as tone-deaf. Timing sends a signal before your words do.",
    impact: "Outreach hold applied in 100% of accounts with detected leadership transitions.",
    graphs: "State \u00b7 Relationship \u00b7 Precedent",
  },
  { id: "s02", agentType: "sales", roles: ["founder","sales","executive"], domains: ["pipeline","finance"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Proposal sent 11 days into their Q4 budget freeze.",
    scenario: "Perfect timing \u2014 prospect said \u2018send us a proposal\u2019 two weeks ago. Sales agent sends it. What no one flagged: their Q4 budget freeze started 11 days ago. No new vendor commitments until Q1. The proposal goes unread.",
    withMemory: "Drafts and sends the proposal based on the last meeting notes. No awareness of external budget conditions at the prospect\u2019s org.",
    withGenios: "State graph: Q4 budget freeze detected at prospect org. Recommends: delay proposal, switch to ROI-forward nurture content until Q1 opens.",
    theOneThing: "A proposal during a budget freeze isn\u2019t rejected \u2014 it\u2019s ignored. That\u2019s worse.",
    whyItMatters: "Sending the right thing at the wrong time trains prospects to deprioritize you. You can\u2019t un-send a proposal that landed in a frozen quarter.",
    impact: "Deal timing accuracy improves by avg 34% when state-aware outreach is applied.",
    graphs: "State \u00b7 Precedent",
  },
  { id: "s03", agentType: "sales", roles: ["sales","founder"], domains: ["pipeline"],
    plan: "early", planLabel: "Early Plan \u00b7 $35 /mo",
    title: "Check-in email sent when you owe them a deck update.",
    scenario: "Deal has been stalled for 3 weeks. Sales agent sends a \u2018just checking in\u2019 email to nudge the prospect. The last exchange ended with you promising to send an updated deck. That was 22 days ago. The check-in arrives before the deck does.",
    withMemory: "Detects the gap in conversation. Drafts a check-in. Sends it. No awareness of what was owed from your side.",
    withGenios: "Precedent graph: last exchange had an open commitment \u2014 deck update, 22 days overdue. Recommends: lead with the commitment, not a check-in. Commitment-led re-engagement has consistently higher close rates than generic follow-ups.",
    theOneThing: "A check-in when you owe something reads as avoidance. Lead with what you owe.",
    whyItMatters: "Stalled deals are rarely stalled by the prospect. Usually there\u2019s an unfulfilled promise on your side that nobody tracked.",
    impact: "Commitment-led re-engagements consistently outperform generic check-ins in stalled deal recovery.",
    graphs: "Precedent \u00b7 Relationship",
  },
  { id: "s04", agentType: "sales", roles: ["sales","executive","founder"], domains: ["pipeline"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Full proposal sent to a contact who can\u2019t say yes.",
    scenario: "Sales agent sends the proposal to Neha, your champion. Three weeks ago the deal escalated internally \u2014 the actual decision is now owned by the VP of Engineering. Neha has influence, not authority. The proposal sits with the wrong person for two weeks.",
    withMemory: "Sends to the stored contact. No awareness that authority has drifted within the account since the last interaction.",
    withGenios: "Authority graph: decision-making shifted to VP of Engineering 3 weeks ago. Champion is now an influencer. Recommends: re-route proposal and loop in the VP directly.",
    theOneThing: "Memory knows who you talked to last. GeniOS knows who can actually say yes now.",
    whyItMatters: "A proposal that lands with the wrong person delays the deal by weeks \u2014 and signals to the account that you don\u2019t know their org.",
    impact: "Authority drift detected in avg 2.1 active accounts per month per sales rep.",
    graphs: "Authority \u00b7 State",
  },
  { id: "s05", agentType: "sales", roles: ["sales","founder","executive"], domains: ["cs","pipeline"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Renewal pitch sent to an account that\u2019s been going cold for 30 days.",
    scenario: "Contract end is 3 weeks out. Sales agent sends the renewal package. Nobody flagged that engagement has dropped 66% over the last month and the main contact hasn\u2019t replied in 21 days. The pitch lands into silence.",
    withMemory: "Detects the renewal date. Sends the renewal package. No context on relationship health or what\u2019s been happening in the account.",
    withGenios: "Relationship graph: 66% engagement drop. State graph: champion silent for 21 days. Recommends: personal outreach from a founder or exec before any renewal pitch.",
    theOneThing: "A renewal pitch to a cooling account doesn\u2019t just fail \u2014 it tells them you weren\u2019t watching.",
    whyItMatters: "Customers who churn rarely complain first. They go quiet. That silence is the only warning you get.",
    impact: "At-risk accounts caught avg 3.2 weeks before renewal conversation, giving recovery time.",
    graphs: "Relationship \u00b7 State \u00b7 Precedent",
  },
  { id: "s06", agentType: "sales", roles: ["sales","founder"], domains: ["pipeline"],
    plan: "early", planLabel: "Early Plan \u00b7 $35 /mo",
    title: "Competitor comparison doc sent to someone who left that competitor badly.",
    scenario: "Sales agent sends a competitor comparison document to a prospect. Your champion spent 4 years at that competitor and left after a very public acquisition dispute. The deck leads with why your competitor is inferior. You lose the meeting before it starts.",
    withMemory: "Pulls the prospect\u2019s profile and recent news. Attaches the deck. No awareness of who the champion actually is or their history.",
    withGenios: "Relationship graph: champion spent 4 years at this competitor \u2014 left following a widely reported dispute. Recommends: remove competitor section, replace with customer-evidence positioning. Direct comparison risks the relationship.",
    theOneThing: "Sending a competitor takedown to someone who left that company badly is the fastest way to lose the room.",
    whyItMatters: "Your champion\u2019s reaction to the first slide determines whether the meeting continues. Sales collateral that works against the relationship is worse than no collateral.",
    impact: "Background-aware content recommendations applied to 100% of configured key-contact profiles.",
    graphs: "Relationship \u00b7 Precedent",
  },
  { id: "s07", agentType: "sales", roles: ["sales","founder"], domains: ["pipeline"],
    plan: "early", planLabel: "Early Plan \u00b7 $35 /mo",
    title: "\u2018Personalized\u2019 outreach with zero actual context.",
    scenario: "Sales agent drafts a \u2018personalized\u2019 email \u2014 name, company, recent funding news, a line about their product. It looks personal. What it misses: this contact met your co-founder at a conference 4 months ago and walked away genuinely impressed.",
    withMemory: "Pulls name and company from CRM. Adds recent news hook. Looks personalized on the surface.",
    withGenios: "Relationship graph: this contact met your co-founder at a conference 4 months ago \u2014 flagged as a warm touchpoint. Recommends: reference that moment. Relationship-grounded opening delivers 3.1\u00d7 reply rate.",
    theOneThing: "Personalization without relationship depth is just mail merge with extra steps.",
    whyItMatters: "Buyers can tell the difference between a templated email and a real one within 2 sentences. True context changes the tone in a way that can\u2019t be faked.",
    impact: "Relationship-grounded outreach averages 3.1\u00d7 reply rate vs. template personalization.",
    graphs: "Relationship \u00b7 Precedent",
  },
  { id: "s08", agentType: "sales", roles: ["sales","executive"], domains: ["pipeline","finance"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Formal quote sent during their 60-day procurement hold.",
    scenario: "Prospect said they\u2019re ready to move. Sales agent sends a formal price quote. What didn\u2019t get communicated: their procurement team is on a 60-day hold following an internal policy change. The quote creates a process friction you now have to undo.",
    withMemory: "Sends the quote as scheduled. No awareness of the prospect\u2019s internal procurement state.",
    withGenios: "State graph: procurement hold active at this org. Recommends: send ROI summary instead of formal quote. Flag for re-approach in 45 days.",
    theOneThing: "A formal quote during a procurement hold creates friction you\u2019ll have to work backwards from.",
    whyItMatters: "Making a prospect explain why they can\u2019t engage trains them to associate your name with process pain.",
    impact: "Timing-aware follow-ups reduce avg sales cycle by 18 days in affected accounts.",
    graphs: "State \u00b7 Precedent",
  },
  { id: "s09", agentType: "sales", roles: ["sales","founder"], domains: ["cs","pipeline"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Upsell email sent while their support ticket is 6 days unresolved.",
    scenario: "Sales agent sends an upsell offer to one of your best accounts. That same account has had an open Priority 1 support ticket for 6 days. Nobody told the sales agent. The account reads the upsell email while waiting for a fix.",
    withMemory: "CRM shows the account as \u2018healthy.\u2019 Upsell goes out. No connection to the open support thread.",
    withGenios: "State graph: active unresolved Priority 1 support ticket \u2014 6 days open. All commercial outreach suppressed automatically. CS team notified for immediate escalation.",
    theOneThing: "Upselling a customer with an open complaint is the clearest signal that your systems don\u2019t talk to each other.",
    whyItMatters: "Nothing destroys enterprise trust faster than being sold to while waiting for a fix. It confirms that your teams don\u2019t share state \u2014 and that the customer\u2019s problem doesn\u2019t actually matter.",
    impact: "Commercial outreach suppressed on 100% of accounts with open priority support tickets.",
    graphs: "State \u00b7 Relationship",
  },
  { id: "s10", agentType: "sales", roles: ["sales","founder","executive"], domains: ["pipeline"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Win-back sequence sent to an account that left over a specific incident.",
    scenario: "Sales agent spots a churned account and launches a win-back sequence. Standard stuff \u2014 new features, updated pricing, a friendly re-intro. What it doesn\u2019t know: this account left over a support SLA breach that happened 3 times and was never properly acknowledged.",
    withMemory: "Finds the account in CRM as \u2018churned.\u2019 Launches a standard win-back. No context on the specific reason they left.",
    withGenios: "Precedent graph: churned 8 months ago \u2014 3 SLA breaches, never escalated or acknowledged. Recommends: lead with a direct acknowledgment of what failed, not with features.",
    theOneThing: "Win-backs that don\u2019t address why they left confirm that nothing has changed.",
    whyItMatters: "Customers who left on bad terms remember exactly what happened. A generic re-intro tells them the org still doesn\u2019t know \u2014 or care.",
    impact: "Reason-aware win-back messaging has 2.8\u00d7 higher re-engagement rate vs. standard sequences.",
    graphs: "Precedent \u00b7 Relationship",
  },

  // \u2500\u2500\u2500 FINANCE AGENT \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

  { id: "f01", agentType: "finance", roles: ["executive","ops","founder"], domains: ["finance"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Payment processed 11 days into an active budget freeze.",
    scenario: "Finance agent processes a routine $12K vendor payment from the queue. A Q4 budget freeze was announced company-wide 11 days ago via email. The agent wasn\u2019t there for that email. Payment goes through.",
    withMemory: "Processes the payment as scheduled. Agents act on queued tasks \u2014 they don\u2019t monitor real-time changes to org budget policy between sessions.",
    withGenios: "State graph: Q4 budget freeze active since Nov 1 \u2014 declared via all-hands. Payment paused automatically. Procurement lead notified with freeze context before any action taken.",
    theOneThing: "A queued payment is a decision made in the past. GeniOS checks whether the org has moved on since.",
    whyItMatters: "An unauthorized payment found in audit is a compliance event, not a process error. Finance agents that can\u2019t read real-time org state are a liability on every cycle.",
    impact: "Zero unauthorized spend during declared freeze periods in orgs with State-graph-connected finance agents.",
    graphs: "State \u00b7 Precedent",
  },
  { id: "f02", agentType: "finance", roles: ["executive","ops"], domains: ["finance"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Payment queued at $14K. CFO threshold is $10K.",
    scenario: "Finance agent queues a $14K vendor payment and processes it. CFO approval is required for anything above $10K \u2014 the policy is in the org\u2019s authority documentation, not in the agent\u2019s prompt. Payment processes without escalation.",
    withMemory: "Processes the payment. No live model of current approval thresholds. The threshold lives in a document the agent was never given.",
    withGenios: "Authority graph queried before processing: $14K exceeds $10K CFO threshold. Payment flagged, CFO notified with context bundle. Processed within 48h after approval.",
    theOneThing: "The threshold is in the Authority graph. Not in the prompt.",
    whyItMatters: "Payments above approval threshold without escalation are audit findings \u2014 regardless of whether the vendor relationship is good or the work was done.",
    impact: "100% of above-threshold payments caught before processing \u2014 zero exceptions.",
    graphs: "Authority \u00b7 Precedent",
  },
  { id: "f03", agentType: "finance", roles: ["executive","ops","founder"], domains: ["finance","ops"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "$84K SaaS renewal in 18 days. Team migrated off it 6 weeks ago.",
    scenario: "Your $84K SaaS contract auto-renews in 18 days. The team migrated off the tool 6 weeks ago \u2014 zero logins since. No one cancelled. Finance agent processes renewals from the queue, no usage signal, no alert.",
    withMemory: "No proactive contract monitoring. Renewals process as scheduled unless someone manually flags them for review.",
    withGenios: "State graph: renewal window opens in 18 days. Usage: zero logins in 43 days. Precedent: 2 similar non-renewals caught and saved $60K+. Alert sent to procurement lead with cancellation recommendation.",
    theOneThing: "Your contract tracker knows the renewal date. GeniOS knows the team stopped using it.",
    whyItMatters: "$84K locks in the moment the window closes. There\u2019s no undo \u2014 you\u2019re committed for another 12 months on a tool nobody opens.",
    impact: "Avg $47K saved per year in detected non-renewal situations across tracked contracts.",
    graphs: "State \u00b7 Precedent",
  },
  { id: "f04", agentType: "finance", roles: ["executive","ops"], domains: ["finance"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Travel reimbursement processed above the cap that changed 3 weeks ago.",
    scenario: "Finance agent processes a $3,200 travel reimbursement. The travel policy cap was updated to $2,500 three weeks ago following a cost review. The agent was working from the previous policy. Reimbursement goes through without a flag.",
    withMemory: "Processes based on prior policy knowledge. No mechanism to detect or ingest policy changes between sessions.",
    withGenios: "Authority graph: travel policy updated 3 weeks ago \u2014 cap now $2,500. Reimbursement flagged for manager review before processing.",
    theOneThing: "Policies update. Memory doesn\u2019t.",
    whyItMatters: "Inconsistent expense enforcement creates compliance exposure and trust issues simultaneously \u2014 some employees get flagged, others don\u2019t, based on when their agent last learned the rules.",
    impact: "Policy violations caught in 100% of cases where Authority graph is updated.",
    graphs: "Authority \u00b7 State",
  },
  { id: "f05", agentType: "finance", roles: ["executive","ops"], domains: ["finance","cs"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Invoice paid to a vendor whose contract expired 18 days ago.",
    scenario: "Finance agent receives an invoice from a vendor and processes it. The vendor\u2019s contract expired 18 days ago and no renewal was executed. No one connected the invoice to the contract status.",
    withMemory: "Processes the invoice as received. No live tracking of vendor contract status outside of what it was explicitly told.",
    withGenios: "State graph: vendor contract expired 18 days ago \u2014 no renewal on file. Invoice flagged, sent to procurement for contract resolution before any payment is processed.",
    theOneThing: "Memory processes invoices. GeniOS checks if you still have a contract first.",
    whyItMatters: "Paying an expired vendor creates financial and potential legal exposure depending on contract terms \u2014 and removes your leverage to renegotiate.",
    impact: "100% of post-contract invoices flagged before payment processing.",
    graphs: "State \u00b7 Authority",
  },
  { id: "f06", agentType: "finance", roles: ["executive","ops"], domains: ["finance"],
    plan: "scale", planLabel: "Scale Plan \u00b7 Custom",
    title: "Payroll file submitted with a contractor who offboarded 6 weeks ago.",
    scenario: "Finance agent prepares the monthly payroll file for bank submission. A contractor on the list officially offboarded 6 weeks ago \u2014 HR updated the system, sent the offboarding email, closed access. The payroll agent\u2019s headcount list never updated.",
    withMemory: "Generates payroll from the employee list in its dataset. Offboarding happened in an HR system the agent wasn\u2019t connected to.",
    withGenios: "State graph: contractor offboarded 6 weeks ago \u2014 cross-referenced against HR records. Payroll line flagged before submission. Finance lead alerted for correction.",
    theOneThing: "Payroll is a legal document. An agent that runs from a stale headcount file creates a compliance exposure on every cycle.",
    whyItMatters: "Paying a former contractor creates immediate tax, legal, and HR complications. Recovery requires multiple teams and takes weeks \u2014 from a list that should have been current.",
    impact: "Stale headcount in payroll files caught before submission in 100% of cases where State graph is current.",
    graphs: "State \u00b7 Authority",
  },
  { id: "f07", agentType: "finance", roles: ["executive","ops"], domains: ["finance"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Paying a vendor mid-dispute removes your only leverage.",
    scenario: "Finance agent queues a $22K payment to a vendor. There\u2019s an active dispute over a failed delivery from last month \u2014 raised in a Slack thread 12 days ago, still unresolved. The agent never saw the Slack thread. Payment processes.",
    withMemory: "Processes the payment as queued. The dispute exists in a channel the agent was never connected to.",
    withGenios: "State graph: active vendor dispute \u2014 raised 12 days ago, unresolved. Payment flagged, routed to procurement lead before processing.",
    theOneThing: "Memory processes what\u2019s in the queue. GeniOS checks what\u2019s in the relationship before it acts.",
    whyItMatters: "Paying a vendor mid-dispute signals the dispute is resolved when it isn\u2019t. You\u2019ve lost your leverage before the negotiation even starts.",
    impact: "Vendor dispute hold applied in 100% of detected active disputes before payment triggers.",
    graphs: "State \u00b7 Relationship",
  },
  { id: "f08", agentType: "finance", roles: ["executive","ops","founder"], domains: ["finance"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Software upgrade approved without the person who owns the budget.",
    scenario: "A team lead requests a $1,200/mo software upgrade. Finance agent processes the approval. The budget owner for that cost center is the VP of Finance \u2014 who requires sign-off on any software above $800/mo. Approval goes through without them.",
    withMemory: "Processes the approval as received. No live model of who owns which budget or what thresholds apply by cost center.",
    withGenios: "Authority graph: software upgrades above $800/mo require VP Finance approval for this cost center. Approval flagged, re-routed to correct authority before processing.",
    theOneThing: "The request looked approved. The Authority graph knew it wasn\u2019t.",
    whyItMatters: "Approvals that bypass the right authority aren\u2019t decisions \u2014 they\u2019re liabilities. They get reversed, create friction, and erode trust in the finance process.",
    impact: "Authority routing accuracy: 100% for configured cost centers.",
    graphs: "Authority \u00b7 State",
  },
  { id: "f09", agentType: "finance", roles: ["executive","ops"], domains: ["finance"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "PO sent to a vendor contact who left 3 months ago.",
    scenario: "Finance agent sends a purchase order to the primary contact at a key vendor. That contact left the vendor 3 months ago. The PO lands in a dead inbox. Nobody follows up. The order disappears for two weeks.",
    withMemory: "Sends to the stored contact email. No monitoring of changes at vendor orgs after the contact was first saved.",
    withGenios: "State graph: vendor contact offboarded 3 months ago \u2014 detected via email bounce pattern. PO automatically re-routed to the vendor\u2019s account manager.",
    theOneThing: "Memory stores contacts. GeniOS notices when they stop being contacts.",
    whyItMatters: "A PO that reaches no one is a PO that disappears \u2014 and a vendor relationship that quietly degrades because your systems were running on stale data.",
    impact: "Avg 4-day PO delay eliminated in orgs with state-aware vendor contact tracking.",
    graphs: "State \u00b7 Relationship",
  },
  { id: "f10", agentType: "finance", roles: ["executive","ops","founder"], domains: ["finance","strategy"],
    plan: "scale", planLabel: "Scale Plan \u00b7 Custom",
    title: "Q1 budget forecast built on headcount that\u2019s 60 days out of date.",
    scenario: "Finance agent builds the Q1 budget forecast. It uses the headcount snapshot from 60 days ago \u2014 3 roles filled since then, 2 new openings added. The CFO reviews a forecast that doesn\u2019t reflect the actual org.",
    withMemory: "Uses the headcount data it was given at setup. No live org model to detect changes between sessions.",
    withGenios: "State graph: headcount updated \u2014 3 roles filled in Oct, 2 new openings added in Nov. Forecast recalculated with live data before the CFO review.",
    theOneThing: "A forecast is only as accurate as the org model underneath it.",
    whyItMatters: "Budget decisions made on 60-day-old headcount create real-money misallocations that take quarters to unwind \u2014 and nobody traces them back to a stale dataset.",
    impact: "Forecast accuracy improves by avg 12% with live-state headcount inputs vs. static snapshots.",
    graphs: "State \u00b7 Precedent",
  },

  // \u2500\u2500\u2500 HR AGENT \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

  { id: "h01", agentType: "hr", roles: ["hr","executive","founder"], domains: ["hiring"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Offer letter sent $15K above the comp cap that changed last quarter.",
    scenario: "HR agent processes the final offer for a senior hire \u2014 $180K base, standard package. Comp policy was updated last quarter: senior hires are capped at $165K until February\u2019s review cycle. Agent was working from the previous policy.",
    withMemory: "Processes the offer as drafted. Policy update happened after the agent\u2019s last context. No live model of current comp policy.",
    withGenios: "Authority graph: comp policy updated Q3 \u2014 senior hire cap $165K until Feb review. Offer flagged before sending. Hiring manager looped in immediately.",
    theOneThing: "The workflow was correct. The policy awareness wasn\u2019t.",
    whyItMatters: "An above-cap offer that has to be walked back damages candidate trust before their first day. Some candidates withdraw rather than renegotiate.",
    impact: "Zero comp policy violations on offers in orgs with live Authority graph comp policies.",
    graphs: "Authority \u00b7 Precedent",
  },
  { id: "h02", agentType: "hr", roles: ["hr","founder","executive"], domains: ["hiring","cs"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Day 4. New hire still can\u2019t log in. SSO was promised by day 1.",
    scenario: "During the new hire kickoff call, your team committed to having SSO access ready by day 1. HR agent is managing the onboarding checklist. It\u2019s day 4. The commitment was made verbally in an email \u2014 no one tracked it, no one followed up.",
    withMemory: "Manages the onboarding checklist. No mechanism to extract and track commitments made verbally or in email threads.",
    withGenios: "Commitment extracted from kickoff email: SSO access by day 1. State graph: day 4, unresolved. Alert sent to IT lead with escalation priority.",
    theOneThing: "Memory manages the process. GeniOS tracks what was promised inside it.",
    whyItMatters: "A new hire who can\u2019t log in on day 1 forms their first impression of the org in that moment. That impression is hard to walk back.",
    impact: "100% of verbal and email onboarding commitments tracked through to resolution.",
    graphs: "Precedent \u00b7 State",
  },
  { id: "h03", agentType: "hr", roles: ["hr","executive"], domains: ["hiring"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Interview invite sent to a candidate who already declined this role 7 months ago.",
    scenario: "HR agent finds a strong senior candidate in the pipeline and sends an interview invite. That candidate declined a nearly identical role 7 months ago \u2014 specifically citing the compensation range. The agent sends the same invite without any adjustment.",
    withMemory: "Finds candidate in ATS as \u2018active.\u2019 Sends the interview invite. No recall of prior rejection.",
    withGenios: "Precedent graph: candidate declined a similar role 7 months ago \u2014 cited \u2018comp range doesn\u2019t match expectations.\u2019 Recommends: re-engage with updated comp range before sending an invite.",
    theOneThing: "Sending the same invite that was already declined tells the candidate you don\u2019t remember them.",
    whyItMatters: "Senior candidates have options. A careless re-invite signals a disorganized recruiting process and wastes goodwill you may have built before.",
    impact: "100% of prior-decline candidates flagged before re-invitation is sent.",
    graphs: "Precedent \u00b7 State",
  },
  { id: "h04", agentType: "hr", roles: ["hr","executive"], domains: ["hiring"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Benefits enrollment email lists two plans that no longer exist.",
    scenario: "HR agent sends the open enrollment email to all employees. Two weeks ago, the benefits policy updated and sunset two plan options. The enrollment email still lists them. Employees try to select a plan that doesn\u2019t exist.",
    withMemory: "Sends the enrollment communication based on the last known benefits policy. No live update detection.",
    withGenios: "Authority graph: benefits policy updated 2 weeks ago \u2014 two plan options sunset. Enrollment email regenerated with current options before sending.",
    theOneThing: "An enrollment email with unavailable options creates a confusion you have to personally fix for every affected employee.",
    whyItMatters: "HR credibility is built on precision. Benefits is exactly where employees expect it \u2014 and exactly where a policy mismatch creates the most visible damage.",
    impact: "Policy-accurate enrollment communications in 100% of configured policy-update scenarios.",
    graphs: "Authority \u00b7 State",
  },
  { id: "h05", agentType: "hr", roles: ["hr","executive"], domains: ["hiring","strategy"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Termination letter drafted while Legal has an active hold on this case.",
    scenario: "HR agent drafts a termination letter for an employee who\u2019s been on a performance plan. The process is correct. What the agent doesn\u2019t know: Legal flagged this case 6 days ago and put an active hold on any employment actions pending a review.",
    withMemory: "Drafts the termination letter per HR process. The legal hold exists in a separate system the agent was never connected to.",
    withGenios: "State graph: active legal hold on this employee \u2014 flagged by Legal 6 days ago. Letter drafting paused. Legal team notified for review before any further action.",
    theOneThing: "HR process can be perfect and still wrong if it doesn\u2019t know what Legal has flagged.",
    whyItMatters: "A termination during an active legal hold creates immediate legal exposure \u2014 regardless of the HR rationale. The process was right; the sequencing wasn\u2019t.",
    impact: "100% of employee actions cross-checked against active legal holds before execution.",
    graphs: "State \u00b7 Authority",
  },
  { id: "h06", agentType: "hr", roles: ["hr","founder"], domains: ["hiring"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "JD published with a salary range from a comp review 8 months ago.",
    scenario: "HR agent posts a new job description. The salary range is pulled from the last comp review \u2014 8 months ago. Market rates for this role have shifted +14% since then. Candidates apply, get to the offer stage, and drop out when the numbers don\u2019t match what was posted.",
    withMemory: "Posts the JD as drafted. No live comp benchmarking or detection of policy updates since the last context.",
    withGenios: "Authority graph: comp review updated 6 weeks ago \u2014 market range for this role adjusted +14%. JD flagged for salary range update before publishing.",
    theOneThing: "A posted salary range is a commitment. An outdated one wastes 4\u20138 weeks of recruiting on candidates who will leave at offer stage.",
    whyItMatters: "Candidates who drop out at offer stage because of a salary mismatch represent 4\u20138 weeks of recruiting time lost \u2014 traced back to a number nobody updated.",
    impact: "100% of job descriptions reviewed against current comp policy before publishing.",
    graphs: "Authority \u00b7 State",
  },
  { id: "h07", agentType: "hr", roles: ["hr","executive"], domains: ["hiring","strategy"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Promotion announcement sent before the manager approved it.",
    scenario: "HR agent sends an internal promotion announcement to the team. The direct manager gave verbal approval but never logged it formally. The written sign-off from VP HR is still pending. The announcement goes out before either is confirmed.",
    withMemory: "Processes the announcement based on workflow status. Verbal approval wasn\u2019t logged \u2014 not in scope to detect.",
    withGenios: "Authority graph: promotion requires direct manager + VP HR written approval. Only one sign-off logged. Announcement paused, missing approval requested.",
    theOneThing: "A promotion announced before the approval chain is complete is a management credibility problem, not a process one.",
    whyItMatters: "Internal announcements can\u2019t be un-sent. A correction damages both HR credibility and the manager\u2019s standing with the team.",
    impact: "100% of internal HR announcements validated against full approval chain before sending.",
    graphs: "Authority \u00b7 State",
  },
  { id: "h08", agentType: "hr", roles: ["hr","executive"], domains: ["hiring"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Background check triggered the moment the interview ended \u2014 before any offer.",
    scenario: "HR agent triggers a background check automatically after an interview completes. The workflow is set up to fire at \u2018interview complete.\u2019 The candidate hasn\u2019t received or accepted a verbal offer yet. Background check kicks off 3 stages too early.",
    withMemory: "Follows the automated trigger: interview complete \u2192 initiate background check. No awareness of what stage the candidate is actually at.",
    withGenios: "State graph: interview completed but verbal offer not yet extended or accepted. Background check initiation flagged as premature. Action blocked until offer acceptance is confirmed.",
    theOneThing: "The right action fired at the wrong stage. GeniOS is the only layer that knows the difference.",
    whyItMatters: "Background checks before offer acceptance can create conditional employment exposure depending on jurisdiction \u2014 and spooks candidates who weren\u2019t expecting it.",
    impact: "Process stage validation applied to 100% of HR workflow trigger points.",
    graphs: "State \u00b7 Authority",
  },
  { id: "h09", agentType: "hr", roles: ["hr","executive","founder"], domains: ["hiring","ops"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Offer generated for a candidate the hiring manager already rejected on Slack.",
    scenario: "HR agent sees the candidate as \u2018active\u2019 in the ATS and advances them to offer stage. Four days ago the hiring manager sent a message in Slack saying \u2018we\u2019re going a different direction on this one.\u2019 The ATS never got that signal.",
    withMemory: "ATS shows candidate as active. Advances to offer generation. Slack-based rejection is invisible.",
    withGenios: "State graph: hiring manager rejection signal detected via Slack 4 days ago \u2014 cross-referenced. Candidate status updated before offer is generated.",
    theOneThing: "The ATS is a system of record. Slack is where decisions actually happen. GeniOS reads both.",
    whyItMatters: "Generating an offer after an informal rejection requires an awkward retraction that damages the candidate\u2019s experience and signals a disorganized process.",
    impact: "Cross-channel rejection signals captured and reflected in candidate state in real-time.",
    graphs: "State \u00b7 Relationship",
  },
  { id: "h10", agentType: "hr", roles: ["hr","executive"], domains: ["hiring","strategy"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Reference check sent to a manager with a documented conflict.",
    scenario: "HR agent sends a reference check request to a candidate\u2019s listed prior manager. What isn\u2019t in the ATS: that manager and the candidate had a documented dispute during a performance review cycle \u2014 captured in an internal HR email thread from 14 months ago.",
    withMemory: "Sends to listed references as provided. No model of relationship dynamics between the reference and the candidate.",
    withGenios: "Relationship graph: prior manager has a flagged conflict with this candidate \u2014 documented in an HR email thread 14 months ago. Recommends: use alternate reference, flag conflict of interest to hiring manager.",
    theOneThing: "A reference check sent to someone with a conflict isn\u2019t a reference check \u2014 it\u2019s a liability.",
    whyItMatters: "A biased reference distorts hiring decisions in both directions \u2014 unfairly screening out a strong candidate or missing a real issue. The cost is a wrong hire or a missed one.",
    impact: "Conflict-of-interest references flagged before check is sent in 100% of Relationship-graph-tracked cases.",
    graphs: "Relationship \u00b7 State",
  },

  // \u2500\u2500\u2500 OPERATIONS AGENT \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

  { id: "o01", agentType: "ops", roles: ["ops","executive","founder"], domains: ["ops","cs"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "CS escalation open. Sales agent sends renewal offer. Same account. Same day.",
    scenario: "Ops agent opens a high-priority escalation for a complaint from Account X \u2014 customer is upset, issue is unresolved. Two hours later, sales agent sends a renewal offer to the same account\u2019s main contact. The customer receives both on the same day.",
    withMemory: "Each agent operates from its own task queue. No shared model of what\u2019s actively happening across the account.",
    withGenios: "State graph: active escalation in progress on Account X \u2014 opened 2 hours ago, unresolved. Sales agent renewal outreach blocked. CS lead notified to coordinate timing.",
    theOneThing: "One team handling a complaint, another sending a renewal offer \u2014 the customer experiences both as the same company.",
    whyItMatters: "A renewal offer arriving while an urgent complaint is being escalated tells the customer exactly how much you\u2019re paying attention. That signal travels faster than the renewal conversation.",
    impact: "Cross-agent account conflicts prevented before customer contact in 100% of detected cases.",
    graphs: "State \u00b7 Relationship",
  },
  { id: "o02", agentType: "ops", roles: ["ops","executive"], domains: ["ops"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Time-sensitive task routed to someone who offboarded 3 weeks ago.",
    scenario: "Ops agent assigns a time-critical deliverable to a team member. That person left the company 3 weeks ago. The task routes to an empty inbox. Nobody follows up. You find out when the deadline passes.",
    withMemory: "Assigns based on the last known org chart. No live model of who is still in the organization.",
    withGenios: "State graph: team member offboarded 3 weeks ago. Assignment automatically redirected to the active team lead. Zero delay.",
    theOneThing: "An org chart is a snapshot. Your ops agents are making decisions based on one.",
    whyItMatters: "A task routed to a former employee doesn\u2019t just get delayed \u2014 it disappears. You find out when the deadline passes and the ops agent has no visibility into why.",
    impact: "100% of task assignments validated against live headcount before routing.",
    graphs: "State \u00b7 Authority",
  },
  { id: "o03", agentType: "ops", roles: ["ops","executive","founder"], domains: ["ops","finance"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Vendor contract auto-renews. Nobody reviewed it. Usage is down 40%.",
    scenario: "A key vendor contract has 14 days left. Auto-renewal is active. Utilization is down 40% from last quarter. No alert has fired. Ops agent isn\u2019t monitoring renewals unless someone explicitly asks it to. The window closes and the contract locks.",
    withMemory: "No proactive contract monitoring. Renewals process unless someone manually reviews and flags them before the window.",
    withGenios: "State graph: renewal window opens in 14 days. Usage down 40% vs. prior quarter. Precedent: 2 similar cases recommended non-renewal. Alert sent to procurement lead automatically.",
    theOneThing: "Ops agents don\u2019t know what they don\u2019t monitor. GeniOS monitors continuously.",
    whyItMatters: "Once a contract auto-renews, you\u2019re committed for another year regardless of usage. The decision point was 14 days earlier and it passed without a flag.",
    impact: "100% of contracts with active renewal windows surface in State graph alerts 14\u201330 days out.",
    graphs: "State \u00b7 Precedent",
  },
  { id: "o04", agentType: "ops", roles: ["ops","executive","founder"], domains: ["ops","strategy"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Custom SLA exception approved. Same exception caused problems 3 times before.",
    scenario: "Ops agent recommends approving a custom SLA exception for a mid-market customer. The request looks reasonable in isolation. Nobody checked: the same exception was approved 3 times in the last 18 months, and all 3 created above-average support burden.",
    withMemory: "Recommends based on current request and general playbook. No access to the history of similar decisions and their outcomes.",
    withGenios: "Precedent graph: 3 custom SLA exceptions in 18 months \u2014 all 3 resulted in elevated support cost. Recommendation adjusted: escalate to VP before approving. Show the pattern.",
    theOneThing: "Without precedent, every exception feels like a one-off. GeniOS shows the pattern.",
    whyItMatters: "Exceptions that look reasonable individually become catastrophic at scale. The pattern is always visible in hindsight \u2014 GeniOS surfaces it in advance.",
    impact: "Precedent-informed decisions reduce exception-related support burden by avg 34%.",
    graphs: "Precedent \u00b7 Authority",
  },
  { id: "o05", agentType: "ops", roles: ["ops","executive"], domains: ["ops"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "Escalation routed to a team lead who changed roles 6 weeks ago.",
    scenario: "Ops agent routes a customer escalation to the team lead \u2014 as per the org chart. That team lead moved to a new role 6 weeks ago. The escalation lands in the wrong place, sits for two days, and the customer notices.",
    withMemory: "Routes based on the last known org structure. No mechanism to detect role changes in real time.",
    withGenios: "State graph: team lead\u2019s role changed 6 weeks ago. New owner identified from Slack signal and email pattern. Escalation re-routed to correct person automatically.",
    theOneThing: "An agent that routes based on a stale org structure isn\u2019t misfiring once \u2014 it\u2019s a systematic misfiring machine.",
    whyItMatters: "Escalations that land with the wrong person don\u2019t just get delayed \u2014 they train your org to distrust agent output.",
    impact: "Org chart accuracy maintained continuously. No manual update cycle required.",
    graphs: "State \u00b7 Authority",
  },
  { id: "o06", agentType: "ops", roles: ["ops","executive"], domains: ["ops","finance"],
    plan: "scale", planLabel: "Scale Plan \u00b7 Custom",
    title: "Data migration triggered while a security freeze is active.",
    scenario: "Ops agent triggers a scheduled data migration workflow. Two days ago the security team declared a system freeze pending a compliance review \u2014 announced in an all-hands Slack message. The agent had no visibility into that channel.",
    withMemory: "Executes the workflow as scheduled. The system freeze exists in a Slack announcement the agent was never connected to.",
    withGenios: "State graph: system freeze active \u2014 declared 2 days ago, security review ongoing. Workflow execution paused. Ops lead notified with freeze context and expected timeline.",
    theOneThing: "Scheduled workflows don\u2019t check if the org decided to stop. GeniOS does.",
    whyItMatters: "Running a data migration during a security freeze can contaminate both the migration and the compliance review simultaneously \u2014 creating two problems from one action.",
    impact: "100% of scheduled workflow executions validated against active org-wide holds before triggering.",
    graphs: "State \u00b7 Authority",
  },
  { id: "o07", agentType: "ops", roles: ["ops","executive"], domains: ["ops"],
    plan: "scale", planLabel: "Scale Plan \u00b7 Custom",
    title: "Weekly metrics report emailed to 3 people who left last quarter.",
    scenario: "Ops agent sends the weekly internal metrics report to the standard distribution list. Three people on that list left the company last quarter. Their emails forward externally or go to inactive inboxes. Internal metrics are now outside the company.",
    withMemory: "Sends to the stored distribution list. No live model of org membership or email activity.",
    withGenios: "State graph: 3 of 11 distribution list members offboarded last quarter. List updated before send. Active members only.",
    theOneThing: "A stale distribution list isn\u2019t just a process problem \u2014 it\u2019s a data governance exposure.",
    whyItMatters: "Internal metrics reports reaching external or forwarded addresses are a security event that nobody intended to trigger. It happens on the cadence of your distribution list.",
    impact: "Distribution list accuracy maintained continuously \u2014 no quarterly cleanup sprint required.",
    graphs: "State \u00b7 Authority",
  },
  { id: "o08", agentType: "ops", roles: ["ops","executive","founder"], domains: ["ops","strategy"],
    plan: "scale", planLabel: "Scale Plan \u00b7 Custom",
    title: "$50K vendor decision escalated to someone without the authority to approve it.",
    scenario: "Ops agent escalates a $50K vendor contract decision to the team lead as per the org chart. Policy requires VP-level approval for any vendor decision above $25K. The team lead approves it. The VP finds out later. The decision has to be re-done.",
    withMemory: "Routes to team lead per org chart. No live model of approval thresholds by decision type or dollar amount.",
    withGenios: "Authority graph: vendor decisions above $25K require VP approval per updated policy. Escalation re-routed to correct authority level with full context bundle.",
    theOneThing: "A decision approved at the wrong level isn\u2019t a decision \u2014 it\u2019s a liability waiting to be re-escalated.",
    whyItMatters: "Every hour between a wrong-authority approval and the correct one is a delay that compounds. And it signals that your ops infrastructure doesn\u2019t know its own rules.",
    impact: "100% of escalations validated against Authority graph thresholds before routing.",
    graphs: "Authority \u00b7 State",
  },
  { id: "o09", agentType: "ops", roles: ["ops","executive"], domains: ["ops","cs"],
    plan: "startup", planLabel: "Startup Plan \u00b7 $149 /mo",
    title: "SLA breach happening across email and Slack. Agent only watches tickets.",
    scenario: "A customer raised a critical issue in the ticket system, then followed up via email, then sent a Slack message to their CSM. Ops agent monitors the ticket system. Email and Slack are invisible. Five days pass. SLA is breached. Customer escalates to your CEO.",
    withMemory: "Tracks tickets in the support system. Email threads and Slack messages from the same customer are in a different system.",
    withGenios: "State graph: same issue detected across 3 channels. Total time since first signal: 5.2 days. SLA breached. CS lead notified immediately with full cross-channel context.",
    theOneThing: "SLA monitoring scoped to one channel misses the breach already happening in another.",
    whyItMatters: "Customers who raised a critical issue in 3 places and got no coordinated response don\u2019t stay customers. And they tell others.",
    impact: "Cross-channel SLA monitoring reduces missed breach detections by avg 67%.",
    graphs: "State \u00b7 Relationship",
  },
  { id: "o10", agentType: "ops", roles: ["ops","executive","founder"], domains: ["ops","strategy"],
    plan: "scale", planLabel: "Scale Plan \u00b7 Custom",
    title: "Agent recommends a geography expansion that failed 18 months ago for specific reasons.",
    scenario: "Ops agent recommends expanding into a new market based on current data and general best practices. Eighteen months ago, the same expansion was attempted and failed \u2014 regulatory gap, wrong local partner, specific cost structure. Nobody told the agent.",
    withMemory: "Recommends based on current market data and its training. No access to what the org has actually tried and what happened.",
    withGenios: "Precedent graph: expansion attempted 18 months ago \u2014 failed on regulatory gap and local partner failure. Recommendation adjusted with specific risk flags from your org\u2019s own attempt.",
    theOneThing: "An org that doesn\u2019t learn from its own history is condemned to repeat it.",
    whyItMatters: "Repeating a failed expansion costs twice \u2014 once for the original failure, once for not learning from it. The precedent was there. Nobody queried it.",
    impact: "100% of strategic recommendations cross-referenced against org precedent before surfacing.",
    graphs: "Precedent \u00b7 State \u00b7 Authority",
  },
];\
"""

content = content[:si] + new_array + content[ei+2:]

# ── OPERATION 2: Add plan CTA to right panel ──────────────────────────────────
old_graphs_end = """                  </div>
                </div>
              </div>
            )}
          </div>
        )}"""

new_graphs_end = """                  </div>
                </div>

                {/* Plan recommendation */}
                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 20px", background: T.ink, marginTop: 8, flexWrap: "wrap", gap: 12 }}>
                  <div>
                    <div style={{ fontFamily: T.mono, fontSize: 8.5, letterSpacing: "0.22em", textTransform: "uppercase", color: "rgba(242,236,228,0.38)", marginBottom: 5 }}>If this is your reality</div>
                    <div style={{ fontFamily: T.display, fontSize: 16, fontWeight: 400, color: T.paper, letterSpacing: "-0.015em", fontVariationSettings: "'opsz' 144, 'SOFT' 30" }}>{scenario.planLabel}</div>
                  </div>
                  <a href="#request-access" style={{ fontFamily: T.mono, fontSize: 9.5, letterSpacing: "0.2em", textTransform: "uppercase", color: T.brass, padding: "10px 18px", border: "0.5px solid " + T.brass, textDecoration: "none", display: "inline-block", flexShrink: 0 }}>
                    Get access \u2192
                  </a>
                </div>
              </div>
            )}
          </div>
        )}"""

if old_graphs_end not in content:
    print("ERROR: graphs end marker not found in JSX")
    sys.exit(1)

content = content.replace(old_graphs_end, new_graphs_end, 1)

with open('src/DemoNavy.jsx', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done! Scenarios replaced + plan CTA added.")
